#define IOCTL_TYPE 40000

#define IOCTL_GET_MODULE_NAME \
    CTL_CODE( IOCTL_TYPE, 0x900, METHOD_BUFFERED, FILE_ANY_ACCESS  )

#define IOCTL_GET_SERVICE_TABLE \
    CTL_CODE( IOCTL_TYPE, 0x902, METHOD_BUFFERED , FILE_ANY_ACCESS  )

#define IOCTL_GET_INT_TABLE \
    CTL_CODE( IOCTL_TYPE, 0x903, METHOD_BUFFERED , FILE_ANY_ACCESS  )

#define DRIVER_FUNC_INSTALL     0x01
#define DRIVER_FUNC_REMOVE      0x02

#define DRIVER_NAME       "lookup"